services:
  fastapi_app:
    build:
      context: ./fast_api
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    working_dir: /code
    volumes:
      - ./fast_api:/code
    environment:
      - PYTHONUNBUFFERED=1

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    volumes:
      - ./openwebui_data:/data
    environment:
      - OLLAMA_BASE_URLS=http://ollama:11434
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    hostname: ollama