import os

MAIL_HOST = "MAIL_HOST"
MAIL_PORT = "MAIL_PORT"
MAIL_USER = "MAIL_USER"
MAIL_PASSWORD = "MAIL_PASSWORD"
OLLAMA_TEST_SERVER_URL = "OLLAMA_TEST_SERVER_URL"

SMB_SERVER_HOST = "SMB_SERVER_IP"
SMB_SERVER_PATH = "SMB_SERVER_PATH"
SMB_SERVER_USER = "SMB_SERVER_USER"
SMB_SERVER_PASSWORD = "SMB_SERVER_PASSWORD"
